version: '3.8'

networks:
  slopcrew-network:
    driver: bridge

services:
  slopcrew-server:
    image: slopcrew-server:local
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42069:42069/udp"
    networks:
      - slopcrew-network
    volumes:
      - ./docker/slop:/slop
    environment:
      - Metrics__Host=graphite
      - Database__DatabasePath=/slop/database.db
    depends_on:
      - graphite

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - "3000:3000"
    networks:
      - slopcrew-network
    volumes:
      - ./docker/grafana/grafana:/var/lib/grafana

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: unless-stopped
    ports:
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - slopcrew-network
    volumes:
      - ./docker/graphite/storage:/opt/graphite/storage
