on: workflow_dispatch
name: Deploy to GitHub & Thunderstore

jobs:
    deploy:
        name: Deploy to GitHub & Thunderstore
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Install .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Build GameNetworkingSockets
              uses: lukka/run-vcpkg@v11
              with:
                  vcpkgGitCommitId: 61f610845fb206298a69f708104a51d651872877
                  runVcpkgInstall: true
              env:
                  VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed

            - name: Copy GameNetworkingSockets
              run: Copy-Item -Path ./vcpkg_installed/*/bin/* -Destination ./libs/GameNetworkingSockets -Recurse -Force

            - name: Setup Bomb Rush Cyberfunk dependencies
              run: ./scripts/gha.ps1

            - name: Build
              run: ./scripts/build.ps1
              env:
                  BRCPath: ${{ github.workspace }}/local/BombRushCyberfunk

            - name: Install tcli
              run: dotnet tool install -g tcli

            - name: Deploy to Thunderstore
              run: ./scripts/thunderstore.ps1
              env:
                  THUNDERSTORE_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}

            - name: Deploy to GitHub
              uses: ncipollo/release-action@v1
              with:
                  artifacts: ./out/plugin.zip
                  bodyFile: ./CHANGELOG.md

            - name: Upload plugin artifact
              uses: actions/upload-artifact@v3
              with:
                  name: plugin
                  path: ./SlopCrew.Plugin/bin/Release/net462

            - name: Upload Thunderstore artifact
              uses: actions/upload-artifact@v3
              with:
                  name: thunderstore
                  path: ./thunderstore
